### ISSUE TITLE
Multiple Follow Options

### ISSUE THREAD

**Issue by ramokz** [ramokz/phantom-camera#40]
# Problem
The current Follow property is effectively a case of “do or do not follow”.

While this enables a `PhantomCamera` to stick to another Node's positional changes, it's also extremely limited in terms of what you can do with it.

Ideally, there should be more flexible options to allow a greater variety of follow logic. This also opens up for other follow behaviour, such as #31.

# Proposed Solution
Add the following Follow behaviours as a dropdown (enum) property option:
- [x] `Disabled` (**Default**) #75  – Disables any follow logic, a Follow Target may still be set
- [x] `Simple Follow` #77  – Sticks to the target `Node` but features offset parameters (how the system currently works), #28 will be affecting this
- [x] `Framed Follow` #78  – Similar to `Follow Follow` but with many additional options, #28 will be affecting this 
- [x] `Glued Follow` #76  – Position follows the exact position of the targeted `Node`
- [x] `Path Track Follow` #31 – Follows a given `Path2D` or `Path3D`
