### ISSUE TITLE
Multiple Look At Options

### ISSUE THREAD

**Issue by ramokz** [ramokz/phantom-camera#62]
# Problem
Similar to #40, there are use cases where having multiple Look At options for a `PhantomCamera3D`.
While there are currently three options `Don't Look At`, `Fixed Look At` and `Look at Group`, there are other types that are worth including.

# Proposed Solution
The new options to include are:
- [x] `Disabled` (**Default**) #80  – Disables any rotation logic, a Look At Target may still be set
- [ ] `Framed Look At` #81 – Allows for a variety of options such as offset (#21), damping (#28) and more. 
- [x] `Fixed Look At` – What the current system is using, glues the `PhantomCamera3D` to look at the target Node
- [x] `Mimic Look At` #79  – Copies the rotational value of the target
- [x] `Group Free Look At` #38  –  Allows for looking at multiple nodes at once. The mode effectively attempts to keep all of them in view.
